export const PUBSUB_KEY = {
  MAINTENANCE_REQUEST_CREATED: 'MAINTENANCE_REQUEST_CREATED',
  MAINTENANCE_REQUEST_UPDATED: 'MAINTENANCE_REQUEST_UPDATED',
  MAINTENANCE_REQUEST_RESOLVED: 'MAINTENANCE_REQUEST_RESOLVED',
  MAINTENANCE_REQUEST_DELETED: 'MAINTENANCE_REQUEST_DELETED',
  MAINTENANCE_REQUEST_RUN_SCHEDULER: 'MAINTENANCE_REQUEST_RUN_SCHEDULER',
}
