import { QueryParamInput, Sort } from './graphql/type.graphql'

export const PUBSUB_KEY = {
  MAINTENANCE_REQUEST_CREATED: 'MAINTENANCE_REQUEST_CREATED',
  MAINTENANCE_REQUEST_UPDATED: 'MAINTENANCE_REQUEST_UPDATED',
  MAINTENANCE_REQUEST_RESOLVED: 'MAINTENANCE_REQUEST_RESOLVED',
  MAINTENANCE_REQUEST_DELETED: 'MAINTENANCE_REQUEST_DELETED',
  MAINTENANCE_REQUEST_RUN_SCHEDULER: 'MAINTENANCE_REQUEST_RUN_SCHEDULER',
}

export const DEFAULT_QUERY_PARAM: QueryParamInput = {
  page: 1,
  perPage: 10,
  sort: Sort.Latest,
  keyword: '',
}
